### PR TITLE
GH-601 Add PlayerArgument, fix /tp command usage.

### LINKED ISSUE #601: Teleport command after lc 3.0 update.
image

### PR DESCRIPTION
**Pull request by vLuckyyy**
Fix #601

### CODE REVIEW

**Review by P1otrulla — APPROVED** [review]

**Review by imDMK — APPROVED** [review]

**Review by igoyek — APPROVED** [review]

**Review by SfenKer — APPROVED** [review]

**Review by Jakubk15 — APPROVED** [review]

File: eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java [hunk 1]
```diff
@@ -77,13 +89,24 @@ void to(@Context Player sender, @Arg Location location, @Arg World world) {
     }
 
     @Execute
-    @DescriptionDocs(description = "Teleport player to specified player, location and world", arguments = "<x> <y> <z> <player> <world>")
-    void to(@Context Viewer sender, @Arg Location location, @Arg Player player, @Arg World world) {
+    @DescriptionDocs(description = "Teleport player to specified location and world", arguments = "<player> <x> <y> <z> <world>")
+    void to(@Context Viewer sender, @Arg Player target, @Arg Location location) {
```
Comment (Rollczi) [inline eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java:93]: missing world argument, I think we can  use optional world argument

File: eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java [hunk 2]
```diff
@@ -55,13 +65,15 @@ void other(@Context Viewer sender, @Arg Player player, @Arg Player target) {
     }
 
     @Execute
-    @DescriptionDocs(description = "Teleport to specified player", arguments = "<player>")
-    void execute(@Context Player sender, @Context Viewer senderViewer, @Arg Player player) {
-        this.teleportService.teleport(sender, player.getLocation());
+    @DescriptionDocs(description = "Teleport to specified location", arguments = "<x> <y> <z>")
+    void to(@Context Player sender, @Arg Location location) {
```
Comment (Rollczi) [inline eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java:69]: you can add optional world argument to the end of the tp command

**Review by Rollczi — CHANGES_REQUESTED** [review]

**Review by Rollczi — APPROVED** [review]
