### PR TITLE
GH-757 Resolve case sensitivity issue in command execution for Minecraft nicknames

### LINKED ISSUE #757: Case (lower/upper/mixed) of the nickname is important in commands.
**Describe the problem**
Minecraft nicknames do not distinguish between different letter cases. For instance, we cannot have two players with nicknames "Abc" and "abc". When using a command that requires a player's nickname as an argument, it's essential to provide the exact same case as the player's nickname. Entering a nickname with different letter cases, e.g., uppercase or lowercase, will result in the command not working.

**Example**
If a player has the nickname "ABC" and we input "abc" in a command, it will not function as expected.

**Request**
We need a solution to make command execution consistent regardless of letter case in player nicknames. 

**Additional Information**
This issue impacts the usability and user experience of the Minecraft server. Resolving this will improve user interaction and command functionality.

### PR DESCRIPTION
**Pull request by vLuckyyy**
Fixes #757

### CODE REVIEW

File: eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java [hunk 1]
```diff
@@ -28,7 +29,10 @@ public PlayerArgument(ViewerService viewerService, TranslationManager translatio
 
     @Override
     public ParseResult<Player> parse(Invocation<CommandSender> invocation, String argument, Translation translation) {
-        Player target = this.server.getPlayer(argument);
+        Player target = this.server.getOnlinePlayers().stream()
+            .filter(player -> player.getName().equalsIgnoreCase(argument))
+            .findFirst()
+            .orElse(null);
```
Comment (imDMK) [inline eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java:35]: This solution is not very efficient. Imagine that this function will be executed 30 times with 1000 people on the server in same time. Use the #getPlayerExact method which searches case insensitively. 


```suggestion
        Player target = this.server.getPlayerExact(argument);
```

**Review by imDMK — CHANGES_REQUESTED** [review]

File: eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java (hunk 1 above)
Comment (vLuckyyy) [reply eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java]: ⚡

**Review by imDMK — APPROVED** [review]

**Review by CitralFlo — APPROVED** [review]

**Review by Jakubk15 — APPROVED** [review]
