### PR TITLE
GH-244 Fix problem with reloading language.yml file (Resolve #238)

### LINKED ISSUE #238: Problem with reloading language.yml file
**Describe the bug**
A problem with reloading language.yml file

**To Reproduce**
1. Make changes in language.yml config
2. Run /eternal reload command

**Expected behavior**
Fix this big bug. It is really annoying -_-

**Platform (please complete the following information):**
 - Java version: "17.0.4.1" 2022-08-18 LTS
 - Server software: PaperMC 1.19.3 build #359

### PR DESCRIPTION
**Pull request by eripe14**
**Please describe the changes made by this PR and why they need to be merged:** 
Fix problem with reloading language.yml file
---
**Status:** Ready and working

### CODE REVIEW

File: eternalcore/src/main/java/com/eternalcode/core/configuration/language/LanguageConfiguration.java [hunk 1]
```diff
@@ -16,8 +22,74 @@ public class LanguageConfiguration implements ReloadableConfig {
...
+    public static class LanguageSelector  {
+
+        @Description({ StringUtils.EMPTY, "# Name of inventory" })
+        public String title = "&6Select a language";
+
+        @Description({ StringUtils.EMPTY, "# Size of inventory" })
+        public int rows = 5;
+
+        @Description({ StringUtils.EMPTY, "# Border settings" })
+        public Border border = new Border();
```
Comment (vLuckyyy) [inline eternalcore/src/main/java/com/eternalcode/core/configuration/language/LanguageConfiguration.java:35]: Przy okazji jak tu jesteś to zmień wszystkie StringUtils.EMPTY na " "

Przykład 👇
```suggestion
        @Description({ " ", "# Name of inventory" })
        public String title = "&6Select a language";

        @Description({ " ", "# Size of inventory" })
        public int rows = 5;

        @Description({ " ", "# Border settings" })
        public Border border = new Border();
```

**Review by vLuckyyy — CHANGES_REQUESTED** [review]

**Review by vLuckyyy — APPROVED** [review]
