### PR TITLE
GH-1214 Allow for more comfort Material argument parsing

### LINKED ISSUE #1214: /item and /give commands does not work if the provided Material is in lowercase
### Expected behavior:
The argument should be passed and the argument should be processed in UPPER_CASE only in the `Material#valueOf` method rather than degrading the UX by disallowing lowercased arguments.

### PR DESCRIPTION
**Pull request by Jakubk15**
Resolves #1214

### CODE REVIEW

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/messages/ArgumentMessages.java [hunk 1]
```diff
@@ -13,6 +13,7 @@ public interface ArgumentMessages {
     Notice numberBiggerThanZero();
     Notice numberBiggerThanOrEqualZero();
     Notice noItem();
+    Notice noMaterial();
```
Comment (Jakubk15) [inline eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/messages/ArgumentMessages.java:16]: this was present **earlier** in the code in **implementations**, just not in the interface

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+        super(translationManager);
+    }
+
+    @Override
+    public ParseResult<Material> parse(Invocation<CommandSender> invocation, String argument, Translation translation) {
+        try {
+            Material material = Material.matchMaterial(argument);
+            return ParseResult.success(material);
+        } catch (IllegalArgumentException exception) {
+            return ParseResult.failure(translation.argument().noMaterial());
```
Comment (imDMK) [inline eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java]: Use Material#valueOf

**Review by imDMK — APPROVED** [review]

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java (hunk 2 above)
Comment (Rollczi) [reply eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java]: Why @imDMK ?

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+    @Inject
+    MaterialArgument(TranslationManager translationManager) {
+        super(translationManager);
+    }
+
+    @Override
+    public ParseResult<Material> parse(Invocation<CommandSender> invocation, String argument, Translation translation) {
+        try {
+            Material material = Material.matchMaterial(argument);
```
Comment (Rollczi) [inline eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java]: Tutaj tak jak gemini powiedział null checka dodaj i nie rób try catch

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    public SuggestionResult suggest(
+        Invocation<CommandSender> invocation,
+        Argument<Material> argument,
+        SuggestionContext context
+    ) {
+        return Arrays.stream(Material.values())
+            .map(Material::name)
+            .map(String::toLowerCase)
+            .collect(SuggestionResult.collector());
+    }
```
[the remark this answers is not in the document]
Comment (Rollczi) [reply eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java:45]: @Jakubk15 zrób tak jak gemini tutaj chciał ogólnie to tych enumów jest tak dużo że trzeba to cachowac

**Review by Rollczi — CHANGES_REQUESTED** [review]
Gemini nawet spoko rzeczy napisał

**Comment by CitralFlo** [comment]
Can we get more creative branch name next time?

File: eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+        return ParseResult.success(material);
+    }
+
+    @Override
+    public SuggestionResult suggest(
+        Invocation<CommandSender> invocation,
+        Argument<Material> argument,
+        SuggestionContext context
+    ) {
+        return CACHED_SUGGESTIONS;
```
Comment (P1otrulla) [inline eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java:44]: We could set a limit for these tabs here and add that it only shows when you give e.g. 1 or 2 first letters of the Material

Comment (Jakubk15) [reply eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/MaterialArgument.java:44]: It has a limit already (set by LC/Minecraft protocol). It's not like the client receives all CACHED_SUGGESTIONS at once.
