### PR TITLE
GH-263 Add target check to open inventory command (Resolve #256)

### LINKED ISSUE #256: Item duplication bug
**Describe the bug**
In /open inventory <player> there is possibility to duplicate item. It happens only if the inventory belongs to the command executor.

https://user-images.githubusercontent.com/65517973/209874030-007b0d84-ffd0-4a20-9bb5-3aad8843c0d6.mp4

**Platform (please complete the following information):**
 - Java Version: 17
 - Server software: PaperMC 1.19.3 build #362

### PR DESCRIPTION
**Pull request by vLuckyyy**
This PR fixes a critical bug where you could copy your items by opening your inventory

### CODE REVIEW

**Review by Jakubk15 — APPROVED** [review]

File: eternalcore/src/main/java/com/eternalcode/core/language/Messages.java [hunk 1]
```diff
@@ -150,6 +150,7 @@ interface OtherMessages {
 
         Notification inventoryClearMessage();
         Notification inventoryClearMessageBy();
+        Notification cantOpenYourInventory();
```
Comment (Rollczi) [inline eternalcore/src/main/java/com/eternalcode/core/language/Messages.java:153]: proszę nie dodwać wiadomości do OtherMessages

**Review by Rollczi — CHANGES_REQUESTED** [review]

**Review by Rollczi — APPROVED** [review]
